name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release-binary:
    name: Release Binary ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            runner: ubuntu-26.04
          - target: aarch64-unknown-linux-gnu
            runner: ubuntu-26.04-arm
    runs-on: ${{ matrix.runner }}
    env:
      RELEASE_TAG: ${{ github.event.release.tag_name }}
    steps:
      - uses: so1ve/workflows/setup-rust@v1
        with:
          toolchain: nightly
      - uses: ./.github/actions/setup-rust-ci
      - run: cargo build --locked --release
      - run: mv target/release/relvi "relvi-${{ matrix.target }}"
      - name: Upload binary
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload "$RELEASE_TAG" "relvi-${{ matrix.target }}" --clobber
